### ISSUE TITLE
KeyError: Cannot draw image in top level window

### ISSUE THREAD

**Issue by chauhannaman98** [chauhannaman98/MedFixture#8]
https://github.com/chauhannaman98/Hospital-Management-System/blob/fcfde9bee45c7a9f0eead3403a136b8ed0e8cfa9/master.py#L165

Error message:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "master.py", line 67, in login
    self.drawWin()
  File "master.py", line 102, in drawWin
    self.drawImage(top)
  File "master.py", line 165, in drawImage
    self.render = ImageTk.PhotoImage(self.file)
  File "/usr/lib/python3/dist-packages/PIL/ImageTk.py", line 114, in __init__
    mode = Image.getmodebase(mode)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 326, in getmodebase
    return ImageMode.getmode(mode).basemode
  File "/usr/lib/python3/dist-packages/PIL/ImageMode.py", line 64, in getmode
    return _modes[mode]
```

**Comment by chauhannaman98** [comment]
Issue resolved in merge pull request [#10](https://github.com/chauhannaman98/Hospital-Management-System/pull/10)
